- hosts: db
  vars_files:
  - vars/db.yaml
  tasks:
  - name: Install dependencies
    become: true
    apt:
      name: 
        - acl
        - postgresql
        - python3-psycopg2
      state: present
      update_cache: true
  
  - name: Config remote conexion
    become: true
    lineinfile:
      path: /etc/postgresql/12/main/pg_hba.conf
      line: "host all all 0.0.0.0/0 md5"
      state: present
      insertafter: EOF

  - name: Enable remote conexion
    become: true
    lineinfile:
      path: /etc/postgresql/12/main/postgresql.conf
      line: "listen_addresses='*'"
      state: present
      insertafter: EOF
  
  - name: Restart postgres
    become: true
    service:
      name: postgresql
      state: restarted
  
  - name: Create sonarqube database
    become: yes
    become_user: postgres
    postgresql_db:
      name: "{{ db_name }}"
  
  - name: Create db user
    become: yes
    become_user: postgres
    postgresql_user:
      name: "{{ db_user }}"
      password: "{{ db_password }}"

  


 